{% set name = "expelliarmus" %}
{% set version = "1.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/expelliarmus-{{ version }}.tar.gz
  sha256: 69978d115af857016b82a78387a4d78ee952ed802998b9cf778feb80393d2c3d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - expelliarmus
  commands:
    - pip check
    - python -c "from expelliarmus import Wizard"
  requires:
    - pip

about:
  home: https://github.com/open-neuromorphic/expelliarmus
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: A Python/C library for decoding DVS binary data formats to NumPy structured arrays.

extra:
  recipe-maintainers:
    - Tobias-Fischer
